
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template
db.url=jdbc:mysql://localhost:3306/tierracolorada_bd?zeroDateTimeBehavior=CONVERT_TO_NULL
db.user=root
db.password=GNRoses40752839?
db.driver=com.mysql.cj.jdbc.Driver


